[package]
edition = "2021"
name = "kilo-ed"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
errno = "0.2.8"
